name: customer_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI/UX Components
  cupertino_icons: ^1.0.8
  flame_lottie: ^0.4.2+18
  iconsax_flutter: ^1.0.1

  # Time-Format
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/anims/

  fonts:
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"